catalog/urls.py
from catalog.apps import CatalogConfig
from django.urls import path

from catalog.views import home, contacts, card

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('<int:pk>/item/', card, name="card")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage

NULLABLE = {'blank': True, 'null': True}
_MAX_SIZE = 300 # максимальный размер изображения


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name="Описание", **NULLABLE)
    preview_image = models.ImageField(upload_to='media/', verbose_name='Превью-изображение', **NULLABLE)
    product_category = models.ForeignKey('Category', on_delete=models.CASCADE, max_length=20, verbose_name = "Категория", **NULLABLE)
    price = models.FloatField(verbose_name = "Стоимость", **NULLABLE)
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name = 'Дата создания', **NULLABLE)
    change_date = models.DateTimeField(auto_now=True, verbose_name = 'Дата изменения', **NULLABLE)

    def __str__(self):
        return f"Продукт {self.title} из категории {self.product_category} по цене {self.price}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('-price',)

class Category(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField(**NULLABLE)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('title',)

class Contact(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=50)
    phone = models.CharField(verbose_name='Телефон', max_length=50)

    def __str__(self):
        return f'Имя: {self.name}, телефон: {self.phone}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('name',)

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import render_to_string

from .models import Product


# Create your views here.
def home(request):
    all_items = Product.objects.all()
    return render(request, 'catalog/home.html', context={"all_items": all_items, "title": "Главная страница"})

def contacts(request):
    if request.method == "POST":
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"Ура! Новый пользователь {name} с телефоном {phone} отправил сообщение: {message}")
    return render(request, 'catalog/contacts.html')

def card(request, pk):
    all_items = Product.objects.filter(id=pk)
    title = all_items[0].title
    return render(request, 'catalog/card.html', context={"all_items": all_items, "title": title})

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="/static/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<div class="row text-center">
    <div class="col-3">
        {% include 'catalog/includes/inc_menu.html' %}
    </div>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - лучший сервис для покупок всего!</p>
</div>

<div class="container">
    <div class="card-deck mb-3 text-center">
{% block content %}
{% endblock%}
    </div>
</div>

<div class="container">
    {% include 'catalog/includes/inc_footer.html' %}
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/card.html
{% extends "catalog/base.html" %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
{% for item in all_items %}
{% include 'catalog/includes/inc_personal_card.html' %}
{% endfor %}
{% endblock content %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% include 'catalog/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <input type="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% include 'catalog/includes/inc_footer.html' %}

</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/includes/inc_card.html
{% load catalog_tags %}
<div class="card mb-4 box-shadow">
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{item.title}}</h4>
        <h5 class="my-0 font-weight-normal">{{item.product_category}}</h5>
    </div>
    <div class="card-body">
        <h1 class="card-title pricing-card-title">RUB {{item.price}}</h1>
        <img src="{% mymedia item.preview_image %}" alt="{{item.title}}" height="200px"/>
        <p>{{item.description|slice:":100"}}</p>
        <a href="{% url 'catalog:card' item.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
    </div>
</div>

catalog/templates/catalog/includes/inc_footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

catalog/templates/catalog/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

catalog/templates/catalog/includes/inc_personal_card.html
{% load catalog_tags %}
<div class="card mb-4 box-shadow">
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{item.title}}</h4>
        <h5 class="my-0 font-weight-normal">{{item.product_category}}</h5>
    </div>
    <div class="card-body">
        <h1 class="card-title pricing-card-title">RUB {{item.price}}</h1>
        <img src="{% mymedia item.preview_image %}" alt="{{item.title}}" height="200px"/>
        <p>{{item.description}}</p>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
    </div>
</div>